### ISSUE TITLE
More specific "Set the config values:"

### ISSUE THREAD

**Issue by diadras** [RobertOstermann/vscode-phpunit-extended#4]
"Set the config values:" is not clear enough to know where to put the config values.
Do you put it next to the other parameters in settings.json?

Thanks :)

I would like to clarify that I know I am supposed to put it into my settings.json file.

**Comment by RobertOstermann** [comment]
@diadras Please take a look at this [Pull Request](https://github.com/RobertOstermann/vscode-phpunit-extended/pull/5) and let me know if those changes are sufficiently clear as to where the config values should be placed.
